import React,{useEffect,useMemo,useState}from'react';import{Home,Users,Ticket,BarChart3,Settings,ArrowLeft}from'lucide-react';import{db,configured}from'./firebase';import{doc,getDoc,setDoc,updateDoc,collection,getDocs,addDoc,query,where,orderBy,limit,serverTimestamp,increment}from'firebase/firestore';
const cats=['勉強','運動','生活','健康','仕事','創作','読書','片付け','その他'];
const examples={勉強:['パソコンを開く','卒論ファイルを開く','教科書を1ページ開く'],運動:['運動着に着替える','靴を履く','ストレッチを1つする'],生活:['食器を1枚片付ける','机の物を1つ戻す'],健康:['水を1杯飲む','体調を一言記録する'],仕事:['必要なファイルを開く','メールを1件確認する'],創作:['制作ソフトを開く','アイデアを1行書く'],読書:['本を開く','1ページだけ読む'],片付け:['物を1つ戻す','ごみを1つ捨てる'],その他:['準備だけする','1分だけ取り組む']};
const presets=['眠い','時間がない','疲れている','気分が乗らない','完璧にできそうにない','今日はもう頑張った','明日の自分が何とかしてくれそう'];
const day=(off=0)=>{const d=new Date();d.setDate(d.getDate()+off);return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(d)};const now=()=>new Date().toISOString();const pc=()=>localStorage.getItem('mindame_code')||'';
async function log(code,name,details={}){try{await addDoc(collection(db,'participants',code,'events'),{participantCode:code,eventName:name,details,createdAt:serverTimestamp()})}catch{}}
async function load(code){const p=await getDoc(doc(db,'participants',code));if(!p.exists())return{registered:false};const ts=await getDocs(collection(db,'participants',code,'tickets'));const tickets=ts.docs.map(x=>({id:x.id,...x.data()}));const rs=await getDocs(query(collection(db,'participants',code,'dailyRecords'),orderBy('recordDate','desc'),limit(7)));const records=rs.docs.map(x=>({id:x.id,...x.data()}));const today=records.find(x=>x.recordDate===day())||null,pending=records.find(x=>x.recordDate<day()&&!x.resultType)||null;return{registered:true,user:p.data(),tickets,records,today,pending}}
function Meter({records=[]}){const r=records.filter(x=>x.actionScore!==null&&x.actionScore!==undefined),v=r.length?Math.round(r.reduce((a,x)=>a+Number(x.actionScore),0)/r.length*100):0,l=r.length<3?'記録をためている途中':v<40?'休みが多め':v<50?'少しゆっくり':v<=70?'ちょうどいい':v<85?'頑張りが多め':'休息も検討';return <div className="card"><div className="meterHead"><div><small>今週のペース</small><strong>{r.length<3?'—':v+'%'}</strong></div><b>{l}</b></div><div className="meter"><i/><i/><i/><span style={{left:`calc(${v}% - 6px)`}}/></div><div className="labels"><em>休み多め</em><em>ちょうどいい</em><em>頑張り多め</em></div></div>}
function Header({title,back,onBack,settings}){return <header>{back&&<button onClick={onBack}><ArrowLeft/></button>}<h1>{title}</h1>{settings&&<button className="right" onClick={settings}><Settings/></button>}</header>}
export default function App(){
  const [code,setCode]=useState(pc());
  const [data,setData]=useState(null);
  const [screen,setScreen]=useState('loading');
  const [tab,setTab]=useState('home');
  const [step,setStep]=useState(0);
  const [form,setForm]=useState({consent:false,category:'勉強',goal:'',minimum:'',tickets:[]});
  const [selected,setSelected]=useState(null);
  const [share,setShare]=useState(false);
  const [message,setMessage]=useState('');

  async function refresh(c=code){
    setScreen('loading');
    const d=await load(c);setData(d);
    if(!d.registered)setScreen('setup');
    else if(d.pending)setScreen('review');
    else if(!d.today)setScreen('predict');
    else setScreen('app');
  }
  useEffect(()=>{if(!configured)setScreen('config');else if(!code)setScreen('code');else refresh(code)},[]);
  if(screen==='config')return <div className="center"><div><h2>Firebase設定が必要です</h2><p>GitHub SecretsへFirebaseのWeb設定を登録してください。</p></div></div>;
  if(screen==='loading')return <div className="center">読み込み中</div>;
  if(screen==='code')return <div className="app"><main><h1 className="logo">みんだめ</h1><p className="muted">行動と休息の、ちょうどいいところへ。</p><div className="card form"><label>参加コード<input id="code" placeholder="MD-001"/></label><p className="muted">同じ端末では、次回から自動的に続きから開きます。</p><button className="primary" onClick={()=>{const c=document.getElementById('code').value.trim().toUpperCase();if(!/^[A-Z0-9_-]{3,20}$/.test(c))return alert('参加コードを確認してください');localStorage.setItem('mindame_code',c);setCode(c);refresh(c)}}>はじめる</button></div></main></div>;
  if(screen==='setup')return <Setup code={code} step={step} setStep={setStep} form={form} setForm={setForm} onDone={()=>refresh()}/>;
  if(screen==='review')return <Review code={code} data={data} onDone={()=>refresh()}/>;
  if(screen==='predict')return <Predict code={code} data={data} selected={selected} setSelected={setSelected} share={share} setShare={setShare} onDone={()=>refresh()}/>;
  if(screen==='done')return <div className="app"><Header title="今日の記録"/><main><div className="card idea"><h2>記録しました</h2><p>{message}</p></div><button className="primary" onClick={()=>setScreen('app')}>ホームへ</button></main></div>;

  const u=data.user; const t=data.today;
  let content=null;
  if(tab==='home')content=<><Header title="みんだめ" settings={()=>setTab('settings')}/><main><p className="eyebrow">目標</p><h2>{u.goalText}</h2><Meter records={data.records}/><div className="card today"><small>今日の言い訳予測</small><b>{t.predictedExcuse}</b><hr/><small>今日の最低ライン</small><b>{u.minimumAction}</b></div>{t.resultType?<div className="card idea"><b>今日は記録済み</b></div>:<><button className="primary" onClick={()=>setTab('score')}>できた</button><button className="secondary" onClick={async()=>{await updateDoc(doc(db,'participants',code,'dailyRecords',day()),{resultType:'rest',actionScore:0,resultRecordedAt:now()});log(code,'intentional_rest_selected');setMessage('今日は休息日として記録しました。');setScreen('done')}}>今日は意識的に休む</button></>}</main></>;
  if(tab==='score')content=<><Header title="どこまでできた？" back onBack={()=>setTab('home')}/><main>{[['予定どおりできた',1],['少し進めた',.75],['最低ラインまでできた',.5]].map(([x,score])=><button key={x} className="choice wide" onClick={async()=>{await updateDoc(doc(db,'participants',code,'dailyRecords',day()),{resultType:score===1?'maximum':score===.75?'medium':'minimum',actionScore:score,resultRecordedAt:now()});log(code,'minimum_action_completed',{score});setMessage('今日のペースに反映しました。');setScreen('done')}}>{x}</button>)}</main></>;
  if(tab==='tickets')content=<><Header title="言い訳チケット一覧"/><main><div className="stack">{data.tickets.map(x=><div key={x.id} className={`ticket ${x.chargeCompleteDate>=day()?'charging':''}`}><div><b>{x.excuseText}</b><small>{x.chargeCompleteDate>=day()?`チャージ中・${x.chargeCompleteDate}まで`:'使用できます'}／使用{x.usageCount||0}回</small></div><Ticket/></div>)}</div></main></>;
  if(tab==='records')content=<><Header title="今のペース"/><main><Meter records={data.records}/><div className="stats">{[['記録日数',data.records.length],['予測一致',data.records.filter(x=>x.predictionMatched===true).length],['最低ライン以上',data.records.filter(x=>Number(x.actionScore)>=.5).length],['休息日',data.records.filter(x=>x.resultType==='rest').length]].map(([a,b])=><div key={a} className="card"><small>{a}</small><strong>{b}</strong></div>)}</div></main></>;
  if(tab==='feed')content=<Feed code={code} category={u.category}/>;
  if(tab==='settings')content=<><Header title="設定" back onBack={()=>setTab('home')}/><main><div className="card"><small>参加コード</small><h3>{code}</h3></div><button className="secondary" onClick={()=>{localStorage.removeItem('mindame_code');location.reload()}}>別の参加コードで始める</button></main></>;
  const showNav=!['score','settings'].includes(tab);
  return <div className="app">{content}{showNav&&<nav>{[['home',Home,'ホーム'],['feed',Users,'みんな'],['tickets',Ticket,'チケット'],['records',BarChart3,'記録']].map(([id,Icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/><span>{label}</span></button>)}</nav>}</div>;
}
function Setup({code,step,setStep,form,setForm,onDone}){async function finish(){await setDoc(doc(db,'participants',code),{participantCode:code,consent:true,category:form.category,goalText:form.goal,minimumAction:form.minimum,onboardingCompleted:true,registeredAt:now(),lastAccessedAt:now()});for(const text of form.tickets)await addDoc(collection(db,'participants',code,'tickets'),{participantCode:code,excuseText:text,normalized:text.normalize('NFKC').replace(/\s/g,'').toLowerCase(),usageCount:0,lastUsedDate:'',chargeCompleteDate:'',createdAt:now(),isActive:true});await log(code,'onboarding_completed');onDone()}
let body;if(step===0)body=<><h2>研究へのご協力のお願い</h2><div className="card"><p>このアプリは大学の卒業論文研究で使用します。記録は参加コードで管理し、本名は収集しません。</p></div><label className="check"><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/>説明を読み、研究参加に同意します。</label></>;if(step===1)body=<><h2>目指すのは5～7割。</h2><div className="card idea"><b>毎日完璧にやる必要はありません。</b><p>行動する日と休む日の両方がある状態を、ちょうどいいペースとして扱います。</p></div><Meter records={[{actionScore:.6},{actionScore:.6},{actionScore:.6}]}/></>;if(step===2)body=<><h2>何を、ゆるく続けたい？</h2><div className="grid">{cats.map(x=><button className={`choice ${form.category===x?'selected':''}`} onClick={()=>setForm({...form,category:x})}>{x}</button>)}</div><label className="field">具体的に何を続けたい？<textarea value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}/></label></>;if(step===3)body=<><h2>調子が悪い日でも、どこまでならできそう？</h2><div className="chips">{examples[form.category].map(x=><button onClick={()=>setForm({...form,minimum:x})}>{x}</button>)}</div><label className="field">最低ライン<textarea value={form.minimum} onChange={e=>setForm({...form,minimum:e.target.value})}/></label></>;if(step===4)body=<><h2>言い訳チケットを2枚作る</h2><div className="chips">{presets.map(x=><button disabled={form.tickets.includes(x)||form.tickets.length>=2} onClick={()=>setForm({...form,tickets:[...form.tickets,x]})}>{x}</button>)}</div><div className="stack">{form.tickets.map(x=><div className="ticket"><b>{x}</b><button onClick={()=>setForm({...form,tickets:form.tickets.filter(t=>t!==x)})}>外す</button></div>)}</div></>;if(step===5)body=<><h2>さあ、ゆるくはじめよう。</h2><div className="card summary"><small>目標</small><b>{form.goal}</b><hr/><small>最低ライン</small><b>{form.minimum}</b>{form.tickets.map(x=><b>{x}</b>)}</div></>;const disabled=(step===0&&!form.consent)||(step===2&&!form.goal)||(step===3&&!form.minimum)||(step===4&&form.tickets.length!==2);return <div className="app"><Header title="最初の設定" back={step>0} onBack={()=>setStep(step-1)}/><main>{body}</main><div className="bottom"><button className="primary" disabled={disabled} onClick={()=>step<5?setStep(step+1):finish()}>{step<5?'次へ':'今日の言い訳を考える'}</button></div></div>}
function Predict({code,data,selected,setSelected,share,setShare,onDone}){const[locked,setLocked]=useState(null),[newText,setNewText]=useState(''),[mode,setMode]=useState('list');async function save(ticket,text,isNew=false){let id=ticket?.id;if(isNew){const ref=await addDoc(collection(db,'participants',code,'tickets'),{participantCode:code,excuseText:text,normalized:text.normalize('NFKC').replace(/\s/g,'').toLowerCase(),usageCount:1,lastUsedDate:day(),chargeCompleteDate:day(4),createdAt:now(),isActive:true});id=ref.id}else await updateDoc(doc(db,'participants',code,'tickets',id),{usageCount:increment(1),lastUsedDate:day(),chargeCompleteDate:day(4)});await setDoc(doc(db,'participants',code,'dailyRecords',day()),{participantCode:code,recordDate:day(),predictedTicketId:id,predictedExcuse:text,resultType:null,actionScore:null,isShared:share,createdAt:now()});if(share)await addDoc(collection(db,'publicPosts'),{category:data.user.category,excuseText:text,createdAt:now(),isVisible:true,reactions:{}});log(code,isNew?'new_excuse_created':'prediction_created');onDone()}
if(mode==='new')return <div className="app"><Header title="別の言い訳" back onBack={()=>setMode('list')}/><main><h2>今日の新しい言い訳は？</h2><label className="field"><input value={newText} maxLength={100} onChange={e=>setNewText(e.target.value)} placeholder="予定より疲れている"/></label><button className="primary" disabled={!newText.trim()} onClick={()=>save(null,newText.trim(),true)}>この言い訳を使う</button></main></div>;
if(mode==='action')return <div className="app"><Header title="最低ラインだけやる" back onBack={()=>setMode('list')}/><main><small>今日の最低ライン</small><h2>{data.user.minimumAction}</h2><button className="primary" onClick={async()=>{await setDoc(doc(db,'participants',code,'dailyRecords',day()),{participantCode:code,recordDate:day(),predictedTicketId:locked.id,predictedExcuse:'言い訳を使わず着手',resultType:'minimum',actionScore:.5,chargedTicketActionSelected:true,createdAt:now(),resultRecordedAt:now()});log(code,'action_selected_instead_of_excuse');onDone()}}>できた</button><button className="secondary" onClick={()=>setMode('new')}>やってみたが難しかった</button></main></div>;
return <div className="app"><Header title="今日の言い訳予測"/><main><h2>今日使いそうな言い訳は？</h2><div className="stack">{data.tickets.map(t=>{const charging=t.chargeCompleteDate>=day();return <button className={`ticket ${charging?'charging':''}`} onClick={()=>charging?(setLocked(t),setMode('locked')):setSelected(t)}><div><b>{t.excuseText}</b><small>{charging?`チャージ中・${t.chargeCompleteDate}まで`:'使用できます'}</small></div></button>})}</div>{mode==='locked'&&<div className="card"><h3>この言い訳チケットはチャージ中</h3><button className="secondary" onClick={()=>setMode('new')}>別の言い訳を考える</button><button className="primary" onClick={()=>setMode('action')}>それなら、最低ラインだけやる</button></div>}<label className="check"><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/>同じジャンルの利用者に匿名で公開する</label>{selected&&<button className="primary" onClick={()=>save(selected,selected.excuseText)}>今日の作戦を決める</button>}</main></div>}
function Review({code,data,onDone}){const[mode,setMode]=useState('start'),[actual,setActual]=useState('');const r=data.pending;async function simple(type,score){await updateDoc(doc(db,'participants',code,'dailyRecords',r.id),{resultType:type,actionScore:score,recordedNextDay:true,resultRecordedAt:now()});onDone()}if(mode==='actual')return <div className="app"><Header title="本当の言い訳"/><main><h2>予測とは別の理由だった。</h2><label className="field"><input value={actual} onChange={e=>setActual(e.target.value)} maxLength={100}/></label><button className="primary" disabled={!actual.trim()} onClick={async()=>{const ref=await addDoc(collection(db,'participants',code,'tickets'),{participantCode:code,excuseText:actual.trim(),normalized:actual.trim().normalize('NFKC').replace(/\s/g,'').toLowerCase(),usageCount:1,lastUsedDate:day(),chargeCompleteDate:day(4),createdAt:now(),isActive:true});await updateDoc(doc(db,'participants',code,'dailyRecords',r.id),{resultType:'none',actionScore:0,actualTicketId:ref.id,actualExcuse:actual.trim(),predictionMatched:false,actualExcuseCreated:true,recordedNextDay:true,resultRecordedAt:now()});onDone()}}>記録する</button></main></div>;if(mode==='match')return <div className="app"><Header title="言い訳の答え合わせ"/><main><h2>「{r.predictedExcuse}」が理由だった？</h2><button className="primary" onClick={async()=>{await updateDoc(doc(db,'participants',code,'dailyRecords',r.id),{resultType:'none',actionScore:0,actualTicketId:r.predictedTicketId,actualExcuse:r.predictedExcuse,predictionMatched:true,recordedNextDay:true,resultRecordedAt:now()});onDone()}}>そうだった</button><button className="secondary" onClick={()=>setMode('actual')}>別の理由だった</button></main></div>;return <div className="app"><Header title="昨日の確認"/><main><h2>昨日はできた？</h2><div className="card"><small>昨日の言い訳予測</small><b>{r.predictedExcuse}</b></div><button className="primary" onClick={()=>simple('minimum',.5)}>できた</button><button className="secondary" onClick={()=>setMode('match')}>できなかった</button><button className="secondary" onClick={()=>simple('rest',0)}>意識的に休んだ</button></main></div>}
function Feed({code,category}){const[items,setItems]=useState([]);useEffect(()=>{getDocs(query(collection(db,'publicPosts'),where('category','==',category),where('isVisible','==',true),limit(20))).then(s=>setItems(s.docs.map(x=>({id:x.id,...x.data()}))))},[]);return <><Header title="みんなの言い訳"/><main><p className="muted">同じジャンルの人が、今日選んだ言い訳。</p><div className="stack">{items.map(x=><div className="card"><small>{x.category}</small><p>{x.excuseText}</p><button className="pill" onClick={async()=>{await updateDoc(doc(db,'publicPosts',x.id),{[`reactions.${code}`]:'relate'});setItems(items.map(i=>i.id===x.id?{...i,reactions:{...(i.reactions||{}),[code]:'relate'}}:i))}}>わかる {Object.values(x.reactions||{}).filter(v=>v==='relate').length}</button></div>)}</div></main></>}
