import React,{useEffect,useMemo,useState}from'react';
import{addDoc,collection,deleteDoc,doc,getDoc,getDocs,limit,query,serverTimestamp,setDoc,updateDoc,where}from'firebase/firestore';
import{db,firebaseReady,ensureAnonymousUser}from'./firebase.js';

const EXCUSES=['眠い','時間がない','疲れている','気分が乗らない','完璧にできそうにない'];
const STEPS={study:['教材を開く','1ページ読む','1問だけ解く'],thesis:['卒論ファイルを開く','昨日の文章を読む','参考文献を1件確認する','1文だけ書く'],exercise:['運動着に着替える','1分だけ身体を動かす','靴を履く'],life:['机の物を1つ戻す','必要な物を1つ準備する','タイマーを1分にする'],other:['必要な画面を開く','道具を1つ準備する','最初の1分だけ始める']};
const LABEL={study:'勉強',thesis:'卒論・研究',exercise:'運動',life:'生活',other:'その他'};
const SK='mindameParticipantCodeV53';
const DEMO_MODE=true;
const clean=v=>v.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,20);
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());

export default function App(){
 const[ready,setReady]=useState(false),[uid,setUid]=useState(''),[code,setCode]=useState(localStorage.getItem(SK)||''),[codeIn,setCodeIn]=useState('');
 const[profile,setProfile]=useState(null),[loading,setLoading]=useState(false),[records,setRecords]=useState([]),[posts,setPosts]=useState([]),[tab,setTab]=useState('home'),[flow,setFlow]=useState(null),[shareDraft,setShareDraft]=useState(null),[toast,setToast]=useState('');
 const msg=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};
 useEffect(()=>{if(!firebaseReady)return;ensureAnonymousUser().then(u=>{setUid(u.uid);setReady(true)})},[]);
 useEffect(()=>{if(ready&&uid&&code)loadAll()},[ready,uid,code]);
 useEffect(()=>{const f=()=>{if(uid&&code&&!flow)loadAll()};document.addEventListener('visibilitychange',f);return()=>document.removeEventListener('visibilitychange',f)},[uid,code,flow]);
 async function loadAll(){
  setLoading(true);
  const pr=doc(db,'participantsV4',uid),ps=await getDoc(pr);setProfile(ps.exists()?ps.data():null);
  if(ps.exists()){const rs=await getDocs(collection(pr,'records'));setRecords(rs.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.recordDate||'').localeCompare(a.recordDate||'')))}
  setLoading(false);
 }
 function enter(){const c=clean(codeIn);if(c.length<3)return msg('参加コードを確認してください。');localStorage.setItem(SK,c);setCode(c)}
 async function onboard(v){const d={...v,ownerUid:uid,participantCode:code,appVersion:4,customExcuses:v.excuses,savedFirstSteps:STEPS[v.category],createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(doc(db,'participantsV4',uid),d);setProfile(d)}
 const pending=records.find(r=>!r.outcomeStatus)||null;
 const current=DEMO_MODE?pending:(records.find(r=>r.recordDate===today())||null);
 async function savePlan(v){
  const id=DEMO_MODE?`${today()}-${Date.now()}`:today(),ref=doc(db,'participantsV4',uid,'records',id);
  if(!DEMO_MODE){const existing=await getDoc(ref);if(existing.exists()){msg('今日の作戦は記録済みです。');setFlow(null);return loadAll()}}
  const d={ownerUid:uid,participantCode:code,appVersion:5.3,recordDate:today(),predictedExcuse:v.excuse,firstStepText:v.step,outcomeStatus:null,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(ref,d);
  const updates={};
  if(v.newExcuse)updates.customExcuses=[...(profile.customExcuses||[]),v.excuse].filter((x,i,a)=>a.indexOf(x)===i).slice(-20);
  updates.savedFirstSteps=[v.step,...(profile.savedFirstSteps||[])].filter((x,i,a)=>a.indexOf(x)===i).slice(0,20);
  await updateDoc(doc(db,'participantsV4',uid),updates);
  setProfile(p=>({...p,...updates}));
  await loadAll();setShareDraft({recordId:id,excuse:v.excuse,step:v.step});setFlow('publish');msg('今日の作戦を記録しました。')
 }
 async function publishExcuse(share){
  if(share)await addDoc(collection(db,'publicPostsV4'),{ownerUid:uid,category:profile.category,goalText:profile.goalText,excuseText:shareDraft.excuse,firstStepText:shareDraft.step,isVisible:true,createdAt:serverTimestamp()});
  setShareDraft(null);setFlow(null);setTab('home');if(share)msg('匿名で共有しました。')
 }
 async function saveReview(v){const ref=doc(db,'participantsV4',uid,'records',pending.id);await updateDoc(ref,{...v,updatedAt:serverTimestamp(),reviewedAt:serverTimestamp()});if(v.addActualToLibrary&&v.actualExcuse){const xs=[...(profile.customExcuses||[]),v.actualExcuse].filter((x,i,a)=>a.indexOf(x)===i).slice(-20);await updateDoc(doc(db,'participantsV4',uid),{customExcuses:xs});setProfile(p=>({...p,customExcuses:xs}))}await loadAll();setFlow(null);setTab('home');msg('振り返りを記録しました。')}
 async function loadCommunity(){const snap=await getDocs(query(collection(db,'publicPostsV4'),where('isVisible','==',true),limit(50)));const all=snap.docs.map(x=>({id:x.id,...x.data()}));await Promise.all(all.map(async p=>{const reactions=await getDocs(collection(db,'publicPostsV4',p.id,'reactions'));p.seedCount=reactions.docs.filter(x=>x.data().type==='seed').length;p.myReaction=reactions.docs.some(x=>x.id===uid&&x.data().type==='seed')?'seed':null}));setPosts(all.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)))}
 useEffect(()=>{if(tab==='community'&&uid)loadCommunity()},[tab,uid]);
 async function react(post){const wasSelected=post.myReaction==='seed';const nextSelected=!wasSelected;setPosts(list=>list.map(p=>p.id===post.id?{...p,myReaction:nextSelected?'seed':null,seedCount:Math.max(0,(p.seedCount||0)+(nextSelected?1:-1))}:p));const ref=doc(db,'publicPostsV4',post.id,'reactions',uid);try{if(wasSelected)await deleteDoc(ref);else await setDoc(ref,{ownerUid:uid,type:'seed',createdAt:serverTimestamp()})}catch(e){setPosts(list=>list.map(p=>p.id===post.id?{...p,myReaction:wasSelected?'seed':null,seedCount:Math.max(0,(p.seedCount||0)+(wasSelected?1:-1))}:p));msg('リアクションを保存できませんでした。')} }
 async function hidePost(post){if(post.ownerUid!==uid)return;await updateDoc(doc(db,'publicPostsV4',post.id),{isVisible:false});await loadCommunity()}
 if(!firebaseReady)return <Shell><Card><h1>Firebase設定を確認してください</h1></Card></Shell>;
 if(!ready)return <Shell><Loading/></Shell>;
 if(!code)return <Shell><Entry value={codeIn} setValue={setCodeIn} enter={enter}/></Shell>;
 if(loading)return <Shell><Loading/></Shell>;
 if(!profile)return <Shell><Onboard submit={onboard}/></Shell>;
 if(flow==='plan')return <Shell><Plan profile={profile} records={records} previous={records[0]?.predictedExcuse} save={savePlan} back={()=>setFlow(null)}/></Shell>;
 if(flow==='publish'&&shareDraft)return <Shell><PublicExcuse draft={shareDraft} profile={profile} publish={publishExcuse}/></Shell>;
 if(flow==='review')return <Shell><Review item={pending} profile={profile} save={saveReview} back={()=>setFlow(null)}/></Shell>;
 return <Shell profile={profile} toast={toast}><div className="page">{tab==='home'&&<Home pending={pending} current={current} records={records} review={()=>setFlow('review')} plan={()=>setFlow('plan')}/>} {tab==='excuses'&&<MyRecords records={records} profile={profile}/>} {tab==='community'&&<Community posts={posts} uid={uid} react={react} hidePost={hidePost}/>}</div><Nav tab={tab} setTab={setTab}/></Shell>
}
function Shell({children,profile,toast}){return <div className="shell"><header><b>みんだめ<span>{DEMO_MODE?'デモ':'v4.1'}</span></b></header><main>{children}</main>{toast&&<div className="toast">{toast}</div>}</div>}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Loading(){return <div className="center"><div className="loader"/><p>今日の記録を確認しています</p></div>}
function Entry({value,setValue,enter}){return <div className="entry"><p className="eyebrow">言い訳と、最初の一歩。</p><h1>みんだめ</h1><label>参加コード<input value={value}onChange={e=>setValue(e.target.value)}placeholder="例：MD-001"/></label><button className="primary"onClick={enter}>はじめる</button><small>本名や学籍番号は入力しないでください。</small></div>}
function Onboard({submit}){const[category,setCategory]=useState('thesis'),[goal,setGoal]=useState(''),[xs,setXs]=useState([]),[extra,setExtra]=useState(''),[ok,setOk]=useState(false);const toggle=x=>setXs(a=>a.includes(x)?a.filter(v=>v!==x):a.length<3?[...a,x]:a);const add=()=>{const x=extra.trim();if(x&&xs.length<3&&!xs.includes(x)){setXs(a=>[...a,x]);setExtra('')}};return <div className="stack"><h1>最初の設定</h1><Card><label className="check"><input type="checkbox"checked={ok}onChange={e=>setOk(e.target.checked)}/>操作記録を研究データとして利用する説明を読み、同意します</label></Card><Card><h2>取り組むこと</h2><div className="chips">{Object.entries(LABEL).map(([k,v])=><button key={k} className={category===k?'chip on':'chip'}onClick={()=>setCategory(k)}>{v}</button>)}</div><label>目標<input value={goal}onChange={e=>setGoal(e.target.value)}placeholder="例：卒業論文を進める"/></label></Card><Card><div className="count-head"><h2>よく使いそうな言い訳を3つ</h2><b>{xs.length}/3</b></div><p className="muted">候補から選んでも、自分で書いてもかまいません。</p><div className="chips">{EXCUSES.map(x=><button key={x} className={xs.includes(x)?'chip on':'chip'}disabled={!xs.includes(x)&&xs.length>=3}onClick={()=>toggle(x)}>{x}</button>)}</div><div className="add-row"><input value={extra}onChange={e=>setExtra(e.target.value)}placeholder="自分の言い訳を書く"maxLength={60}/><button className="secondary"disabled={!extra.trim()||xs.length>=3}onClick={add}>追加</button></div>{xs.length>0&&<div className="selected-list">{xs.map(x=><button key={x}onClick={()=>setXs(a=>a.filter(v=>v!==x))}>{x}<span>×</span></button>)}</div>}</Card><button className="primary"disabled={!ok||!goal||xs.length!==3}onClick={()=>submit({category,goalText:goal,excuses:xs})}>設定を保存</button></div>}
function Home({pending,current,records,review,plan}){const stats=useMemo(()=>{let moved=0,match=0,other=0;records.forEach(r=>{if(r.outcomeStatus==='acted')moved++;else if(r.outcomeStatus==='not_done'&&r.predictionMatched==='yes')match++;else if(r.outcomeStatus==='not_done'&&r.predictionMatched==='no')other++});return{moved,match,other,total:moved+match+other}},[records]);return <div className="stack"><div><p className="eyebrow">ホーム</p><h1>今日の記録</h1></div><Card className={pending?'attention':''}><h2>振り返り</h2>{pending?<><p className="pair"><span>予測</span><b>{pending.predictedExcuse}</b></p><p className="pair"><span>最初の一歩</span><b>{pending.firstStepText}</b></p><button className="primary"onClick={review}>振り返る</button></>:<p className="muted">振り返る記録はありません。</p>}</Card><Card><h2>今日の予測・作戦</h2>{current?<><p className="pair"><span>予測</span><b>{current.predictedExcuse}</b></p><p className="pair"><span>最初の一歩</span><b>{current.firstStepText}</b></p><span className="done">記録済み</span></>:<><p>今日、できなさそうな理由と最初の一歩を記録します。</p><button className="primary"onClick={plan}>今日の作戦を考える</button></>}</Card><Pattern stats={stats}/></div>}
function Pattern({stats}){if(!stats.total)return <Card><h2>最近の予測と実際</h2><p className="muted">記録が増えると、ここに内訳が表示されます。</p></Card>;return <Card><h2>最近の予測と実際</h2><div className="bar"><i className="moved"style={{width:`${stats.moved/stats.total*100}%`}}/><i className="match"style={{width:`${stats.match/stats.total*100}%`}}/><i className="other"style={{width:`${stats.other/stats.total*100}%`}}/></div><div className="legend"><span><i className="dot moved"/>それでも動けた <b>{stats.moved}</b></span><span><i className="dot match"/>予測どおり <b>{stats.match}</b></span><span><i className="dot other"/>別の理由 <b>{stats.other}</b></span></div></Card>}
function Plan({profile,records,previous,save,back}){const[e,setE]=useState(''),[other,setOther]=useState(''),[step,setStep]=useState(''),[custom,setCustom]=useState(''),[confirm,setConfirm]=useState(false);const opts=[...new Set([...(profile.customExcuses||[]),...EXCUSES])];const excuse=other.trim()||e,first=custom.trim()||step,repeated=excuse&&excuse===previous;const stepStats=useMemo(()=>{const map={};records.forEach((r,i)=>{if(!r.firstStepText)return;const o=map[r.firstStepText]||{text:r.firstStepText,count:0,last:0};o.count++;o.last=Math.max(o.last,Number((r.createdAt?.seconds||0)*1000)||records.length-i);map[r.firstStepText]=o});return Object.values(map)},[records]);const recent=[...stepStats].sort((a,b)=>b.last-a.last).slice(0,3).map(x=>x.text);const frequent=[...stepStats].sort((a,b)=>b.count-a.count||b.last-a.last).map(x=>x.text).filter(x=>!recent.includes(x)).slice(0,3);const recommended=[...new Set(STEPS[profile.category]||[])].filter(x=>!recent.includes(x)&&!frequent.includes(x)).slice(0,4);const StepGroup=({title,items})=>items.length?<div className="step-group"><h3>{title}</h3><div className="choices">{items.map(x=><button key={x}className={step===x?'choice on':'choice'}onClick={()=>{setStep(x);setCustom('')}}>{x}</button>)}</div></div>:null;return <div className="stack"><button className="back"onClick={back}>← ホームへ</button><h1>今日の予測・作戦</h1><Card><h2>今日、使いそうな言い訳は？</h2><div className="chips">{opts.map(x=><button key={x}className={e===x?'chip on':'chip'}onClick={()=>{setE(x);setOther('');setConfirm(false)}}>{x}{x===previous&&<small>前回も使用</small>}</button>)}</div><label>ほかの言い訳<input value={other}onChange={x=>{setOther(x.target.value);setE('')}}/></label>{repeated&&!confirm&&<div className="notice"><p>前回も「{excuse}」でした。</p><button className="secondary"onClick={()=>setConfirm(true)}>同じ理由で記録</button></div>}</Card>{excuse&&(!repeated||confirm||other)&&<Card><h2>「{excuse}」の日、最初に何をする？</h2><StepGroup title="最近使ったもの" items={recent}/><StepGroup title="よく使うもの" items={frequent}/><StepGroup title="おすすめ" items={recommended}/><label>自分で書く<input value={custom}onChange={x=>{setCustom(x.target.value);setStep('')}}placeholder="例：参考文献を1件確認する"/></label></Card>}<button className="primary"disabled={!excuse||!first||(repeated&&!confirm)}onClick={()=>save({excuse,step:first,newExcuse:!!other.trim()})}>記録する</button></div>}
function PublicExcuse({draft,profile,publish}){return <div className="stack"><p className="eyebrow">お楽しみ・任意</p><h1>今日の予測・作戦を共有する？</h1><Card><p className="muted">参加者に匿名で表示されます。個人が分かる内容が含まれていないか確認してください。</p><div className="share-context"><span className={'genre '+profile.category}>{LABEL[profile.category]||'その他'}</span><strong>{profile.goalText}</strong></div><div className="share-preview"><span>今日の予測</span><b>「{draft.excuse}」</b><i>→</i><span>最初の一歩</span><b>{draft.step}</b></div></Card><button className="primary" onClick={()=>publish(true)}>匿名で共有する</button><button className="secondary" onClick={()=>publish(false)}>共有しない</button></div>}
function Review({item,profile,save,back}){const[status,setStatus]=useState(''),[continued,setContinued]=useState(false),[match,setMatch]=useState(''),[actual,setActual]=useState(''),[addActual,setAddActual]=useState(true);const actualOptions=[...new Set([...(profile.customExcuses||[]),...EXCUSES])];return <div className="stack"><button className="back"onClick={back}>← ホームへ</button><h1>振り返り</h1><Card><p className="pair"><span>予測</span><b>{item.predictedExcuse}</b></p><p className="pair"><span>最初の一歩</span><b>{item.firstStepText}</b></p></Card><Card><h2>できましたか？</h2><div className="choices"><button className={status==='acted'?'choice on':'choice'}onClick={()=>setStatus('acted')}>できた</button><button className={status==='not_done'?'choice on':'choice'}onClick={()=>setStatus('not_done')}>できなかった</button></div><div className="minor"><button onClick={()=>setStatus('changed')}>予定が変わった</button><button onClick={()=>setStatus('unknown')}>今回は答えない</button></div></Card>{status==='acted'&&<Card><h2>どこまで進みましたか？</h2><div className="choices"><button className={!continued?'choice on':'choice'}onClick={()=>setContinued(false)}>決めた一歩まで</button><button className={continued?'choice on':'choice'}onClick={()=>setContinued(true)}>その先も続けた</button></div></Card>}{status==='not_done'&&<Card><h2>できなかった理由に「{item.predictedExcuse}」は当てはまりましたか？</h2><div className="choices"><button className={match==='yes'?'choice on':'choice'}onClick={()=>setMatch('yes')}>当てはまった</button><button className={match==='no'?'choice on':'choice'}onClick={()=>setMatch('no')}>別の理由だった</button><button className={match==='unknown'?'choice on':'choice'}onClick={()=>setMatch('unknown')}>よく分からない</button></div>{match==='no'&&<><h3>実際には、どの理由が近かったですか？</h3><div className="chips">{actualOptions.map(x=><button key={x}className={actual===x?'chip on':'chip'}onClick={()=>setActual(x)}>{x}</button>)}</div><label>ほかの理由<input value={actual}onChange={e=>setActual(e.target.value)}placeholder="例：時間がなかった"/></label><label className="check"><input type="checkbox"checked={addActual}onChange={e=>setAddActual(e.target.checked)}/>この理由を言い訳集にも追加する</label></>}</Card>}<button className="primary"disabled={!status||(status==='not_done'&&!match)||(match==='no'&&!actual.trim())}onClick={()=>save({outcomeStatus:status,continuedBeyondFirstStep:status==='acted'&&continued,predictionMatched:status==='not_done'?match:null,actualExcuse:match==='yes'?item.predictedExcuse:match==='no'?actual.trim():null,addActualToLibrary:match==='no'&&addActual})}>保存する</button></div>}
function MyRecords({records,profile}){const[view,setView]=useState('reasons');return <div className="stack"><div><p className="eyebrow">自分の記録</p><h1>{view==='reasons'?'できなかった理由':'踏み出せた一歩'}</h1></div><div className="record-switch"><button className={view==='reasons'?'on':''}onClick={()=>setView('reasons')}>できなかった理由</button><button className={view==='steps'?'on':''}onClick={()=>setView('steps')}>踏み出せた一歩</button></div>{view==='reasons'?<ReasonList records={records} profile={profile}/>:<StepList records={records}/>}</div>}
function ReasonList({records,profile}){const data=useMemo(()=>{const map={};(profile.customExcuses||[]).forEach(x=>{if(x)map[x]=0});const add=x=>{if(!x)return;map[x]=(map[x]||0)+1};records.forEach(r=>{if(r.outcomeStatus!=='not_done')return;if(r.predictionMatched==='yes')add(r.predictedExcuse);if(r.predictionMatched==='no')add(r.actualExcuse)});return Object.entries(map).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'ja'))},[records,profile]);return <><p className="muted">実際にできなかった理由として記録された回数が多い順です。</p>{data.length===0?<Card><p className="muted">まだ登録された言い訳がありません。</p></Card>:data.map((x,i)=><Card key={x.name}><div className="rank"><b>{i+1}</b><h2>{x.name}</h2><strong>{x.count}回</strong></div></Card>)}</>}
function StepList({records}){const data=useMemo(()=>{const map={};records.forEach((r,i)=>{if(!r.firstStepText)return;const x=map[r.firstStepText]||{name:r.firstStepText,setCount:0,doneCount:0,continuedCount:0,last:0};x.setCount++;x.last=Math.max(x.last,r.createdAt?.seconds||records.length-i);if(r.outcomeStatus==='acted'){x.doneCount++;if(r.continuedBeyondFirstStep)x.continuedCount++}map[r.firstStepText]=x});return Object.values(map).sort((a,b)=>b.doneCount-a.doneCount||b.continuedCount-a.continuedCount||b.last-a.last)},[records]);return <><p className="muted">実際にできた回数が多い順です。まだできていない一歩も、設定した記録として残ります。</p>{data.length===0?<Card><p className="muted">まだ最初の一歩を設定した記録がありません。</p></Card>:data.map((x,i)=><Card key={x.name}><div className="rank"><b>{i+1}</b><h2>{x.name}</h2><strong>{x.doneCount}回</strong></div><div className="step-stats"><span>設定した <b>{x.setCount}</b></span><span>できた <b>{x.doneCount}</b></span><span>その先も続いた <b>{x.continuedCount}</b></span></div></Card>)}</>}
function Community({posts,uid,react,hidePost}){const[filter,setFilter]=useState('all');const shown=filter==='all'?posts:posts.filter(p=>p.category===filter);return <div className="stack"><div><p className="eyebrow">みんなの記録</p><h1>予測と最初の一歩</h1><p className="muted">すべての記録を見ることも、ジャンルごとに絞ることもできます。</p></div><div className="genre-filters"><button className={filter==='all'?'chip on':'chip'}onClick={()=>setFilter('all')}>すべて</button>{Object.entries(LABEL).map(([key,label])=><button key={key}className={filter===key?'chip on':'chip'}onClick={()=>setFilter(key)}>{label}</button>)}</div>{shown.length===0?<Card><p className="muted">このジャンルには、まだ共有された記録がありません。</p></Card>:shown.map(p=><Post key={p.id}post={p}uid={uid}react={react}hidePost={hidePost}/>)}</div>}
function Post({post,uid,react,hidePost}){return <Card className="post"><div className="post-head"><span className={'genre '+post.category}>{LABEL[post.category]||'その他'}</span><strong title={post.goalText||''}>{post.goalText||'目標は未登録'}</strong>{post.ownerUid===uid&&<small className="yours">あなたの記録</small>}</div><div className="community-plan"><b>「{post.excuseText}」</b><span>→</span><strong>{post.firstStepText||'最初の一歩は未登録'}</strong></div><div className="reacts"><button aria-label="芽リアクション" className={post.myReaction==='seed'?'selected seed-button':''}onClick={()=>react(post)}>🌱 <span>{post.seedCount||0}</span></button></div>{post.ownerUid===uid&&<button className="hide"onClick={()=>hidePost(post)}>共有を取り消す</button>}</Card>}
function Nav({tab,setTab}){return <nav><button className={tab==='home'?'on':''}onClick={()=>setTab('home')}><span>⌂</span>ホーム</button><button className={tab==='excuses'?'on':''}onClick={()=>setTab('excuses')}><span>▣</span>自分の記録</button><button className={tab==='community'?'on':''}onClick={()=>setTab('community')}><span>◌</span>みんな</button></nav>}
