import React,{useEffect,useMemo,useState}from'react';
import{addDoc,collection,deleteDoc,doc,getDoc,getDocs,limit,query,serverTimestamp,setDoc,updateDoc,where}from'firebase/firestore';
import{db,firebaseReady,ensureAnonymousUser}from'./firebase.js';

const EXCUSES=['眠い','時間がない','疲れている','気分が乗らない','完璧にできそうにない'];
const STEPS={study:['教材を開く','1ページ読む','1問だけ解く'],thesis:['卒論ファイルを開く','昨日の文章を読む','参考文献を1件確認する','1文だけ書く'],exercise:['運動着に着替える','1分だけ身体を動かす','靴を履く'],life:['机の物を1つ戻す','必要な物を1つ準備する','タイマーを1分にする'],other:['必要な画面を開く','道具を1つ準備する','最初の1分だけ始める']};
const LABEL={study:'勉強',thesis:'卒論・研究',exercise:'運動',life:'生活',other:'その他'};
const SK='mindameParticipantCodeV41';
const DEMO_MODE=true;
const clean=v=>v.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,20);
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());

export default function App(){
 const[ready,setReady]=useState(false),[uid,setUid]=useState(''),[code,setCode]=useState(localStorage.getItem(SK)||''),[codeIn,setCodeIn]=useState('');
 const[profile,setProfile]=useState(null),[loading,setLoading]=useState(false),[records,setRecords]=useState([]),[posts,setPosts]=useState([]),[tab,setTab]=useState('home'),[flow,setFlow]=useState(null),[shareDraft,setShareDraft]=useState(null),[toast,setToast]=useState('');
 const msg=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};
 useEffect(()=>{if(!firebaseReady)return;ensureAnonymousUser().then(u=>{setUid(u.uid);setReady(true)})},[]);
 useEffect(()=>{if(ready&&uid&&code)loadAll()},[ready,uid,code]);
 useEffect(()=>{const f=()=>{if(uid&&code&&!flow)loadAll()};document.addEventListener('visibilitychange',f);return()=>document.removeEventListener('visibilitychange',f)},[uid,code,flow]);
 async function loadAll(){
  setLoading(true);
  const pr=doc(db,'participantsV4',uid),ps=await getDoc(pr);setProfile(ps.exists()?ps.data():null);
  if(ps.exists()){const rs=await getDocs(collection(pr,'records'));setRecords(rs.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.recordDate||'').localeCompare(a.recordDate||'')))}
  setLoading(false);
 }
 function enter(){const c=clean(codeIn);if(c.length<3)return msg('参加コードを確認してください。');localStorage.setItem(SK,c);setCode(c)}
 async function onboard(v){const d={...v,ownerUid:uid,participantCode:code,appVersion:4,customExcuses:v.excuses,savedFirstSteps:STEPS[v.category],createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(doc(db,'participantsV4',uid),d);setProfile(d)}
 const pending=records.find(r=>!r.outcomeStatus)||null;
 const current=DEMO_MODE?pending:(records.find(r=>r.recordDate===today())||null);
 async function savePlan(v){
  const id=DEMO_MODE?`${today()}-${Date.now()}`:today(),ref=doc(db,'participantsV4',uid,'records',id);
  if(!DEMO_MODE){const existing=await getDoc(ref);if(existing.exists()){msg('今日の作戦は記録済みです。');setFlow(null);return loadAll()}}
  const d={ownerUid:uid,participantCode:code,appVersion:4.1,recordDate:today(),predictedExcuse:v.excuse,firstStepText:v.step,outcomeStatus:null,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(ref,d);
  if(v.newExcuse){const xs=[...(profile.customExcuses||[]),v.excuse].filter((x,i,a)=>a.indexOf(x)===i).slice(-15);await updateDoc(doc(db,'participantsV4',uid),{customExcuses:xs});setProfile(p=>({...p,customExcuses:xs}))}
  await loadAll();setShareDraft({recordId:id,excuse:v.excuse,step:v.step});setFlow('publish');msg('今日の作戦を記録しました。')
 }
 async function publishExcuse(mode,text){
  if(mode!=='none')await addDoc(collection(db,'publicPostsV4'),{ownerUid:uid,category:profile.category,originalExcuse:shareDraft.excuse,excuseText:mode==='original'?shareDraft.excuse:text.trim().slice(0,60),publicTextMode:mode,isVisible:true,createdAt:serverTimestamp()});
  setShareDraft(null);setFlow(null);setTab('home');if(mode!=='none')msg('匿名で公開しました。')
 }
 async function saveReview(v){const ref=doc(db,'participantsV4',uid,'records',pending.id);await updateDoc(ref,{...v,updatedAt:serverTimestamp(),reviewedAt:serverTimestamp()});await loadAll();setFlow(null);setTab('home');msg('振り返りを記録しました。')}
 async function loadCommunity(){const s=await getDocs(query(collection(db,'publicPostsV4'),where('isVisible','==',true),limit(50)));const all=s.docs.map(x=>({id:x.id,...x.data()}));for(const p of all){const rr=await getDoc(doc(db,'publicPostsV4',p.id,'reactions',uid));p.myReaction=rr.exists()?rr.data().type:null;const rp=await getDocs(query(collection(db,'publicPostsV4',p.id,'replies'),limit(30)));p.replies=rp.docs.map(x=>({id:x.id,...x.data()}))}setPosts(all.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)))}
 useEffect(()=>{if(tab==='community'&&uid)loadCommunity()},[tab,uid]);
 async function react(post,type){const ref=doc(db,'publicPostsV4',post.id,'reactions',uid);if(post.myReaction===type){await deleteDoc(ref)}else await setDoc(ref,{ownerUid:uid,type,createdAt:serverTimestamp()});await loadCommunity()}
 async function reply(post,text){if(!text.trim())return;await setDoc(doc(db,'publicPostsV4',post.id,'replies',uid),{ownerUid:uid,text:text.trim().slice(0,60),createdAt:serverTimestamp()});await loadCommunity()}
 async function removeReply(post){await deleteDoc(doc(db,'publicPostsV4',post.id,'replies',uid));await loadCommunity()}
 async function hidePost(post){if(post.ownerUid!==uid)return;await updateDoc(doc(db,'publicPostsV4',post.id),{isVisible:false});await loadCommunity()}
 if(!firebaseReady)return <Shell><Card><h1>Firebase設定を確認してください</h1></Card></Shell>;
 if(!ready)return <Shell><Loading/></Shell>;
 if(!code)return <Shell><Entry value={codeIn} setValue={setCodeIn} enter={enter}/></Shell>;
 if(loading)return <Shell><Loading/></Shell>;
 if(!profile)return <Shell><Onboard submit={onboard}/></Shell>;
 if(flow==='plan')return <Shell><Plan profile={profile} previous={records[0]?.predictedExcuse} save={savePlan} back={()=>setFlow(null)}/></Shell>;
 if(flow==='publish'&&shareDraft)return <Shell><PublicExcuse draft={shareDraft} publish={publishExcuse}/></Shell>;
 if(flow==='review')return <Shell><Review item={pending} profile={profile} save={saveReview} back={()=>setFlow(null)}/></Shell>;
 return <Shell profile={profile} toast={toast}><div className="page">{tab==='home'&&<Home pending={pending} current={current} records={records} review={()=>setFlow('review')} plan={()=>setFlow('plan')}/>} {tab==='excuses'&&<ExcuseBook records={records} profile={profile}/>} {tab==='community'&&<Community posts={posts} uid={uid} same={profile.category} react={react} reply={reply} removeReply={removeReply} hidePost={hidePost}/>}</div><Nav tab={tab} setTab={setTab}/></Shell>
}
function Shell({children,profile,toast}){return <div className="shell"><header><b>みんだめ<span>{DEMO_MODE?'デモ':'v4.1'}</span></b></header><main>{children}</main>{toast&&<div className="toast">{toast}</div>}</div>}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Loading(){return <div className="center"><div className="loader"/><p>今日の記録を確認しています</p></div>}
function Entry({value,setValue,enter}){return <div className="entry"><p className="eyebrow">言い訳と、最初の一歩。</p><h1>みんだめ</h1><label>参加コード<input value={value}onChange={e=>setValue(e.target.value)}placeholder="例：MD-001"/></label><button className="primary"onClick={enter}>はじめる</button><small>本名や学籍番号は入力しないでください。</small></div>}
function Onboard({submit}){const[category,setCategory]=useState('thesis'),[goal,setGoal]=useState(''),[xs,setXs]=useState(['眠い','時間がない']),[extra,setExtra]=useState(''),[ok,setOk]=useState(false);const toggle=x=>setXs(a=>a.includes(x)?a.filter(v=>v!==x):[...a,x].slice(0,5));return <div className="stack"><h1>最初の設定</h1><Card><label className="check"><input type="checkbox"checked={ok}onChange={e=>setOk(e.target.checked)}/>操作記録を研究データとして利用する説明を読み、同意します</label></Card><Card><h2>取り組むこと</h2><div className="chips">{Object.entries(LABEL).map(([k,v])=><button className={category===k?'chip on':'chip'}onClick={()=>setCategory(k)}>{v}</button>)}</div><label>目標<input value={goal}onChange={e=>setGoal(e.target.value)}placeholder="例：卒業論文を進める"/></label></Card><Card><h2>よく使いそうな言い訳</h2><div className="chips">{EXCUSES.map(x=><button className={xs.includes(x)?'chip on':'chip'}onClick={()=>toggle(x)}>{x}</button>)}</div><label>ほかの言い訳<input value={extra}onChange={e=>setExtra(e.target.value)}/></label></Card><button className="primary"disabled={!ok||!goal||xs.length<2}onClick={()=>submit({category,goalText:goal,excuses:extra?[...xs,extra]:xs})}>設定を保存</button></div>}
function Home({pending,current,records,review,plan}){const stats=useMemo(()=>{let moved=0,match=0,other=0;records.forEach(r=>{if(r.outcomeStatus==='acted')moved++;else if(r.outcomeStatus==='not_done'&&r.predictionMatched==='yes')match++;else if(r.outcomeStatus==='not_done'&&r.predictionMatched==='no')other++});return{moved,match,other,total:moved+match+other}},[records]);return <div className="stack"><div><p className="eyebrow">ホーム</p><h1>今日の記録</h1></div><Card className={pending?'attention':''}><h2>振り返り</h2>{pending?<><p className="pair"><span>予測</span><b>{pending.predictedExcuse}</b></p><p className="pair"><span>最初の一歩</span><b>{pending.firstStepText}</b></p><button className="primary"onClick={review}>振り返る</button></>:<p className="muted">振り返る記録はありません。</p>}</Card><Card><h2>今日の予測・作戦</h2>{current?<><p className="pair"><span>予測</span><b>{current.predictedExcuse}</b></p><p className="pair"><span>最初の一歩</span><b>{current.firstStepText}</b></p><span className="done">記録済み</span></>:<><p>今日、止まりそうな理由と最初の一歩を記録します。</p><button className="primary"onClick={plan}>今日の作戦を考える</button></>}</Card><Pattern stats={stats}/></div>}
function Pattern({stats}){if(!stats.total)return <Card><h2>最近の予測と実際</h2><p className="muted">記録が増えると、ここに内訳が表示されます。</p></Card>;return <Card><h2>最近の予測と実際</h2><div className="bar"><i className="moved"style={{width:`${stats.moved/stats.total*100}%`}}/><i className="match"style={{width:`${stats.match/stats.total*100}%`}}/><i className="other"style={{width:`${stats.other/stats.total*100}%`}}/></div><div className="legend"><span><i className="dot moved"/>それでも動けた <b>{stats.moved}</b></span><span><i className="dot match"/>予測どおり <b>{stats.match}</b></span><span><i className="dot other"/>別の理由 <b>{stats.other}</b></span></div></Card>}
function Plan({profile,previous,save,back}){const[e,setE]=useState(''),[other,setOther]=useState(''),[step,setStep]=useState(''),[custom,setCustom]=useState(''),[confirm,setConfirm]=useState(false);const opts=[...new Set([...(profile.customExcuses||[]),...EXCUSES])];const excuse=other.trim()||e,first=custom.trim()||step,repeated=excuse&&excuse===previous;return <div className="stack"><button className="back"onClick={back}>← ホームへ</button><h1>今日の予測・作戦</h1><Card><h2>今日、使いそうな言い訳は？</h2><div className="chips">{opts.map(x=><button className={e===x?'chip on':'chip'}onClick={()=>{setE(x);setOther('');setConfirm(false)}}>{x}{x===previous&&<small>前回も使用</small>}</button>)}</div><label>ほかの言い訳<input value={other}onChange={x=>{setOther(x.target.value);setE('')}}/></label>{repeated&&!confirm&&<div className="notice"><p>前回も「{excuse}」でした。</p><button className="secondary"onClick={()=>setConfirm(true)}>同じ理由で記録</button></div>}</Card>{excuse&&(!repeated||confirm||other)&&<Card><h2>「{excuse}」の日、最初に何をする？</h2><div className="choices">{[...new Set([...(profile.savedFirstSteps||[]),...STEPS[profile.category]])].slice(0,7).map(x=><button className={step===x?'choice on':'choice'}onClick={()=>{setStep(x);setCustom('')}}>{x}</button>)}</div><label>自分で書く<input value={custom}onChange={x=>{setCustom(x.target.value);setStep('')}}/></label></Card>}<button className="primary"disabled={!excuse||!first||(repeated&&!confirm)}onClick={()=>save({excuse,step:first,newExcuse:!!other.trim()})}>記録する</button></div>}
function PublicExcuse({draft,publish}){const[mode,setMode]=useState('none'),[text,setText]=useState('');return <div className="stack"><p className="eyebrow">お楽しみ・任意</p><h1>みんな向けに公開する？</h1><Card><p className="pair"><span>元の言い訳</span><b>{draft.excuse}</b></p><p className="muted">研究用の記録は保存済みです。ここで書く文章は、お楽しみ用として別に保存されます。</p></Card><Card><div className="choices"><button className={mode==='original'?'choice on':'choice'} onClick={()=>setMode('original')}>そのまま公開</button><button className={mode==='rewritten'?'choice on':'choice'} onClick={()=>setMode('rewritten')}>ネタにして公開</button><button className={mode==='none'?'choice on':'choice'} onClick={()=>setMode('none')}>公開しない</button></div>{mode==='rewritten'&&<label>公開用の言い訳ネタ<input value={text} maxLength={60} onChange={e=>setText(e.target.value)} placeholder="例：布団が私を離してくれない"/><small>{text.length}/60文字　個人が分かる内容は書かないでください。</small></label>}</Card><button className="primary" disabled={mode==='rewritten'&&!text.trim()} onClick={()=>publish(mode,text)}>{mode==='none'?'ホームへ':'匿名で公開する'}</button></div>}
function Review({item,profile,save,back}){const[status,setStatus]=useState(''),[continued,setContinued]=useState(false),[match,setMatch]=useState(''),[actual,setActual]=useState('');return <div className="stack"><button className="back"onClick={back}>← ホームへ</button><h1>振り返り</h1><Card><p className="pair"><span>予測</span><b>{item.predictedExcuse}</b></p><p className="pair"><span>最初の一歩</span><b>{item.firstStepText}</b></p></Card><Card><h2>できましたか？</h2><div className="choices"><button className={status==='acted'?'choice on':'choice'}onClick={()=>setStatus('acted')}>できた</button><button className={status==='not_done'?'choice on':'choice'}onClick={()=>setStatus('not_done')}>できなかった</button></div><div className="minor"><button onClick={()=>setStatus('changed')}>予定が変わった</button><button onClick={()=>setStatus('unknown')}>今回は答えない</button></div></Card>{status==='acted'&&<Card><h2>どこまで進みましたか？</h2><div className="choices"><button className={!continued?'choice on':'choice'}onClick={()=>setContinued(false)}>決めた一歩まで</button><button className={continued?'choice on':'choice'}onClick={()=>setContinued(true)}>その先も続けた</button></div></Card>}{status==='not_done'&&<Card><h2>できなかった理由に「{item.predictedExcuse}」は当てはまりましたか？</h2><div className="choices"><button className={match==='yes'?'choice on':'choice'}onClick={()=>setMatch('yes')}>当てはまった</button><button className={match==='no'?'choice on':'choice'}onClick={()=>setMatch('no')}>別の理由だった</button><button className={match==='unknown'?'choice on':'choice'}onClick={()=>setMatch('unknown')}>よく分からない</button></div>{match==='no'&&<label>実際の理由<input value={actual}onChange={e=>setActual(e.target.value)}placeholder="例：時間がなかった"/></label>}</Card>}<button className="primary"disabled={!status||(status==='not_done'&&!match)||(match==='no'&&!actual)}onClick={()=>save({outcomeStatus:status,continuedBeyondFirstStep:status==='acted'&&continued,predictionMatched:status==='not_done'?match:null,actualExcuse:match==='yes'?item.predictedExcuse:match==='no'?actual:null})}>保存する</button></div>}
function ExcuseBook({records,profile}){const data=useMemo(()=>{const map={};[...(profile.customExcuses||[]),...EXCUSES].forEach(x=>map[x]={name:x,uses:0,moved:0,match:0,other:0});records.forEach(r=>{const o=map[r.predictedExcuse]||{name:r.predictedExcuse,uses:0,moved:0,match:0,other:0};o.uses++;if(r.outcomeStatus==='acted')o.moved++;if(r.outcomeStatus==='not_done'&&r.predictionMatched==='yes')o.match++;if(r.outcomeStatus==='not_done'&&r.predictionMatched==='no')o.other++;map[r.predictedExcuse]=o});return Object.values(map).sort((a,b)=>b.uses-a.uses)},[records,profile]);return <div className="stack"><div><p className="eyebrow">言い訳集</p><h1>自分の言い訳</h1></div>{data.map((x,i)=><Card><div className="rank"><b>{i+1}</b><h2>{x.name}</h2><strong>{x.uses}回</strong></div>{x.uses>0&&<div className="mini"><span>それでも動けた {x.moved}</span><span>予測どおり {x.match}</span><span>別の理由 {x.other}</span></div>}</Card>)}</div>}
function Community({posts,uid,same,react,reply,removeReply,hidePost}){const[filter,setFilter]=useState('all');const shown=posts.filter(p=>filter==='all'||p.category===same);return <div className="stack"><div><p className="eyebrow">お楽しみ</p><h1>みんなの言い訳</h1><p className="muted">あるある＝自分にもありそう／ないない＝自分にはなさそう</p></div><div className="chips"><button className={filter==='all'?'chip on':'chip'}onClick={()=>setFilter('all')}>すべて</button><button className={filter==='same'?'chip on':'chip'}onClick={()=>setFilter('same')}>同じジャンル</button></div>{shown.map(p=><Post key={p.id}post={p}uid={uid}react={react}reply={reply}removeReply={removeReply}hidePost={hidePost}/>)}</div>}
function Post({post,uid,react,reply,removeReply,hidePost}){const[text,setText]=useState('');return <Card className="post"><span className={'genre '+post.category}>{LABEL[post.category]||'その他'}</span>{post.ownerUid===uid&&<small className="yours">あなたの投稿</small>}<p className="posttext">{post.excuseText}</p><div className="reacts"><button className={post.myReaction==='aruaru'?'selected':''}onClick={()=>react(post,'aruaru')}>あるある</button><button className={post.myReaction==='nainai'?'selected':''}onClick={()=>react(post,'nainai')}>ないない</button></div><details><summary>ひとこと返す・返信を見る</summary>{(post.replies||[]).map(r=><div className="reply"><span>{r.text}</span>{r.ownerUid===uid&&<button onClick={()=>removeReply(post)}>削除</button>}</div>)}{!post.replies?.some(r=>r.ownerUid===uid)&&<div className="replyform"><input value={text}maxLength={60}onChange={e=>setText(e.target.value)}placeholder="個人が分かる内容は書かないでください"/><button onClick={()=>{reply(post,text);setText('')}}>送る</button></div>}</details>{post.ownerUid===uid&&<button className="hide"onClick={()=>hidePost(post)}>公開を取り消す</button>}</Card>}
function Nav({tab,setTab}){return <nav><button className={tab==='home'?'on':''}onClick={()=>setTab('home')}><span>⌂</span>ホーム</button><button className={tab==='excuses'?'on':''}onClick={()=>setTab('excuses')}><span>▣</span>言い訳集</button><button className={tab==='community'?'on':''}onClick={()=>setTab('community')}><span>◌</span>みんな</button></nav>}
